version: 1.2.{build}

image: Ubuntu

build:
  verbosity: minimal
  
install:
  - sh: git clone -b %APPVEYOR_REPO_BRANCH% --recurse-submodules https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - sh: git checkout -q %APPVEYOR_REPO_COMMIT%
  - sh: git submodule update --init --recursive
