version: 1.2.{build}

image: Ubuntu

# branches to build
branches:
  # whitelist
  only:
    - master
    - feature/refactor1_2

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

install:
   - sh: git submodule update --init --recursive --force
   - sh: git submodule sync
